# Dependencies
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            The OME Blog
tagline:          'Because metadata is worth a thousand pictures'
url:              http://blog.openmicroscopy.org
repository:       ome/blog
baseurl:          ''

author:
  name:           'The OME Team'
  url:            https://twitter.com/openmicroscopy

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/ome/blog
future: true