---
name: Build

on: 
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
            sudo apt-get update
            sudo apt-get install -y --no-install-recommends \
             python3-pip xvfb qt5-default xkb-data x11-xkb-utils
      - name: Build
        run: |
          docker run --rm -v $PWD:/srv/jekyll -eJEKYLL_UID=$UID jekyll/builder:pages jekyll build
          docker run --rm -v $(pwd)/_site:/site jekyll/builder:pages /usr/gem/bin/htmlproofer /site --disable-external
      - name: Capture page as PDF
        run: |
            export DISPLAY=localhost:1.0
            export QT_XKB_CONFIG_ROOT=/usr/share/X11/xkb
            xvfb-run make capture_pdf
            pkill -f jekyll;
