---
name: Build

on: 
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
            sudo apt-get update
            sudo apt-get install -y --no-install-recommends xvfb
      - name: setup-conda
        uses: s-weigand/setup-conda@v1.0.5
        with:
          python-version: 3.6
      - name: Install weasyprint
        run: |
          conda install -c conda-forge weasyprint
      - name: Build
        run: |
          docker run --rm -v $PWD:/srv/jekyll -eJEKYLL_UID=$UID jekyll/builder:pages jekyll build
          docker run --rm -v $(pwd)/_site:/site jekyll/builder:pages /usr/gem/bin/htmlproofer /site --disable-external
      - name: Capture page as PDF
        run: |
          export DISPLAY=localhost:1.0
          xvfb-run make capture_pdf
      - name: Check output
        run: ls
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          path: "*.pdf"
          if-no-files-found: error
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          path: "*.zip"
          if-no-files-found: error


