---
name: Build

on: 
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
            sudo apt-get install -y --no-install-recommends xfonts-75dpi xfonts-base\
            python3-pip xvfb
            
            wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.focal_amd64.deb
            sudo dpkg -i wkhtmltox_0.12.6-1.focal_amd64.deb
            pip3 install --user --upgrade pip
            pip3 install --user requests
            pip3 install --user coloredlogs
      - name: Build
        run: |
          docker run --rm -v $PWD:/srv/jekyll -eJEKYLL_UID=$UID jekyll/builder:pages jekyll build
          docker run --rm -v $(pwd)/_site:/site jekyll/builder:pages /usr/gem/bin/htmlproofer /site --disable-external
      - name: Capture page as PDF
        run: |
            export DISPLAY=localhost:1.0
            export QT_XKB_CONFIG_ROOT=/usr/share/X11/xkb
            xvfb-run make capture_pdf
            pkill -f jekyll;
